baseURL = "https://example.org/"
languageCode = "en-us"
theme = "hugo-library-theme"
title = "Books of Jane Austen"

[params]
  author = "First Last"
  description = "Some books of Jane Austen"
  dateFormat = "2006-01-02"
  footer1 = "Awesome Books"
  footer2 = "(c) Cool Books"
